#!/bin/bash
source tag-methods

[[ -z ${GIT_USER} || -z ${GIT_PASS} ]] && echo "missing git creds!" && exit 1

IFSBAK=$IFS
IFS="
"
for r in $(cat repos | grep -v "^\s*#") ; do
    repo_name=$(echo $r | cut -d " " -f 1)
    tag_method=$(echo $r | cut -d " " -f 2)
    git clone --depth=1 https://${GIT_USER}:${GIT_PASS}@${repo_name} && cd `basename ${repo_name}`
    newtag=`$tag_method`
    git tag $newtag
    git push --tags 
    cd ..
done
IFS=$IFSBAK
