#!/bin/bash -x

## year.month-counter
md(){
    giturl=$(git remote show origin | grep -i fetch | awk '{print $3}')
    [[ -z "`echo $giturl | grep github`" ]] && echo "'md' tagging method currently works only with github repos, terminating." && exit 1
    prevV=$(git ls-remote -t $giturl | awk '{print $2}' | cut -d '/' -f 3 | grep -v "\-rc" | cut -d '^' -f 1 | sed 's/^v//' | sort -bt- -k1nr -k2nr | grep $tag_prefix | head -1)
    ## prev date
    prevD=`echo $prevV | cut -d- -f1`
    ## prev build number
    prevN=`echo $prevV | cut -d- -f2`
    ## gen new release number
    newD=`date +%y.%m`
    if [[  $prevD == $newD  ]]; then
        newN=$((prevN + 1))
    else
        newN=0
    fi
    newV=$newD-$newN
    echo "$newV"
}
